---
 - name: Print env variable #name description 
   shell: echo $PATH  #shel commans
   register: print_result #what this does is to register the result for the shell script

 - name: print message #i
   debug:
     msg: "{{ print_result.stdout_lines }}" # here we print out the env. variable of the files path for stdout_lines, if you remove this 
     # section then you have what is displayed below >>

      # "stdout": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin",
      
      #   "stdout_lines": [
      #       "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"